version: "3.7"
services:
  ipfs-daemon:
    image: ipfs/go-ipfs:v0.8.0
    volumes:
      - ~/ipfs/ipfs_staging:/export
      - ~/ipfs/ipfs_data:/data/ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    command: ["daemon", "--enable-pubsub-experiment"]
    logging:
      driver: "none"
  app:
    build: .
    network_mode: "service:ipfs-daemon"
    environment:
      SEED: ${SEED}
      DEVICE_ID: ${DEVICE_ID}
